version: "3.9"

services:
  trb-core-back:
    container_name: trb-core-back
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - trb-core-db
    env_file:
      - .env
  trb-core-db:
    container_name: trb-core-db
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5430:5432"
    volumes:
      - trb-core-db:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  trb-core-db: { }