version: "3.9"

services:
  backend:
    container_name: trb-core-back
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    container_name: trb-core-db
    image: postgres:16.2
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - .env