version: "3.9"

services:
  postgres:
    container_name: trb-core-db-dev
    image: postgres:15
    environment:
      POSTGRES_DB: trb-core
      POSTGRES_USER: trb-core
      POSTGRES_PASSWORD: trb-core
    ports:
      - "5400:5432"
    volumes:
      - trb-core-db-dev:/var/lib/postgresql/data

volumes:
  trb-core-db-dev: { }