version: "3.9"

services:
  trb-core-db-dev:
    container_name: trb-core-db-dev
    image: postgres:15
    hostname: postgres
    environment:
      POSTGRES_DB: trb-core
      POSTGRES_USER: trb-core
      POSTGRES_PASSWORD: trb-core
    ports:
      - "5400:5432"
    volumes:
      - trb-core-db-dev:/var/lib/postgresql/data
  trb-zookeeper-dev:
    container_name: trb-zookeeper-dev
    image: confluentinc/cp-zookeeper:7.6.0
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  trb-kafka-1-dev:
    container_name: trb-kafka-1-dev
    image: confluentinc/cp-kafka:7.6.0
    hostname: kafka1
    depends_on:
      - trb-zookeeper-dev
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9000
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:29092,OUTSIDE://localhost:9000
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  trb-kafka-2-dev:
    container_name: trb-kafka-2-dev
    image: confluentinc/cp-kafka:7.6.0
    hostname: kafka2
    depends_on:
      - trb-zookeeper-dev
    ports:
      - "9001:9001"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9001
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka2:29092,OUTSIDE://localhost:9001
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
  kafka-ui-dev:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui-dev
    hostname: kafka-ui
    ports:
      - "8999:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=dev
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:29092,kafka2:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - trb-zookeeper-dev
      - trb-kafka-1-dev
      - trb-kafka-2-dev

volumes:
  trb-core-db-dev: { }