server:
  port: 8080
spring:
  application:
    name: trb-core
  datasource:
    url: jdbc:postgresql://trb-core-db:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    locations: migrations
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
    producer:
      client-id: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
    consumer:
      client-id: ${spring.application.name}
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    org:
      springframework:
        web:
          filter:
            org:
              springframework:
                web:
                  filter:
                    CommonsRequestLoggingFilter: DEBUG

kafka:
  topic:
    consumer:
      transaction-initialization: "transaction.initialization"
    producer:
      transaction-callback: "transaction.callback"
      loan-payment-callback: "transaction.loan.payment-callback"
      loan-repayment-callback: "transaction.loan.repayment-callback"

random-error:
  is-enable: true
  probability-average: 0.5
  probability-extreme: 0.9
  extreme-period-duration-min: 1
  extreme-period-frequency-min: 2

urls:
  exchange-rate: https://api.coingate.com

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - prometheus
  metrics:
    tags:
      application: ${spring.application.name}