server:
  port: 8080
spring:
  application:
    name: trb-core
  datasource:
    url: jdbc:postgresql://postgres:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    locations: migrations