spring:
  datasource:
    url: jdbc:postgresql://localhost:5400/trb-core
    username: trb-core
    password: trb-core
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true